# Setup
title: Journey's Tech Blog :)
description: Junior Data engineer Journey-Kim's Tech Blog
url: https://Youyeon-Journey-Kim.github.io
avatar: /profile.jpg
paginate: 10
permalink: pretty
cover_image: /background.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: Journey
  card: summary
logo: logo.png
social:
  name: Journey Kim
  links:
    - https://twitter.com/vszhub
    - https://github.com/Youyeon-Journey-Kim
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Youyeon-Kim(Journey-Kim)
  url: https://github.com/Youyeon-Journey-Kim/
  email: flex_kim97@naver.com
